### ISSUE TITLE
Occurrence summary error

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/web_app#50]
Why does the occurrence summary for this collection show that Bregmaceros is unclassified...

![unclassified](https://cloud.githubusercontent.com/assets/19557452/25708243/f006447a-30b3-11e7-8dd5-f229d01828e0.jpeg)

When it is actually completely classified:

![bregmaceros](https://cloud.githubusercontent.com/assets/19557452/25708255/f85ad9ce-30b3-11e7-9fdb-c0e045dff050.jpeg)

**Comment by mmcclenn** [comment]
That's because 'Bregmaceros filamentosus' is assigned to 'Problennius' by opinion # 641757.This takes precedence over opinion # 641758 that recombines it from 'Problennius filamentosus' to 'Bregmaceros filamentosus'.  The genus 'Problennius' has no opinions, and thus is not placed in the hierarchy. The simple solution is to either raise the reliability score of the latter or lower that of the former.

  -- Michael



On May 4, 2017, at 9:25 AM, Mark D. Uhen <notifications@github.com<mailto:notifications@github.com>> wrote:


Why does the occurrence summary for this collection show that Bregmaceros is unclassified...

[unclassified]<https://cloud.githubusercontent.com/assets/19557452/25708243/f006447a-30b3-11e7-8dd5-f229d01828e0.jpeg>

When it is actually completely classified:

[bregmaceros]<https://cloud.githubusercontent.com/assets/19557452/25708255/f85ad9ce-30b3-11e7-9fdb-c0e045dff050.jpeg>
